### ISSUE TITLE
.thyme-tmux neede

### ISSUE THREAD

**Issue by lalitmee** [dhammafarer/dotfiles-termux#1]
Hey, I was configuring my tmux. Then I saw this file called **.thyme-tmux**. Can you please give me the content of this file. My tmux is almost configured but the rightmost part is not there.

It would be great if you can provide that file. **Thank you so much.**

**Comment by palekiwi** [comment]
Hi, .thyme-tmux is a file generated by the thyme package (https://github.com/hughbien/thyme) when this package is running. Thyme is a pomodoro timer and it creates the file, then it writes the remaining time to this file at an interval. If you aren't using Thyme, then you can simply delete this block from the config.

**Comment by lalitmee** [comment]
Actually, I am using Ubuntu 16.04 and I don't know anything about thyme. I can show you my tmux. It's having its powerline some kind of in weird condition. In the config file of tmux I saw a command **cat ~/.thyme-tmux** which is driving me crazy. 

You can look that right status is not in its right position. I want that it should touch to the right.
![tmux](https://user-images.githubusercontent.com/10762218/36013085-2ba46816-0d88-11e8-8b05-4451f7137a62.png)
